{% set name = "hcrystalball" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dab4527bba16529c5b0d2ac6128b8ef26324be6d124d4f2746922ac5c0a2db36

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pyscaffold >=3.1a0,<3.2a0
  run:
    - python >=3.7
    - numpy
    - pandas >=1.0
    - scipy >=1.4
    - scikit-learn >=0.23
    - workalendar >=10.1

test:
  imports:
    - hcrystalball
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heidelbergcement/hcrystalball
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A time series library that unifies the API for most commonly used libraries and modelling techniques for time-series forecasting in the Python ecosystem.

extra:
  recipe-maintainers:
    - michalchromcak
